name: Build Custom Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: LibreChat image tag
        required: true
        default: v0.7.5
      mongo:
        description: Mongo image tag
        required: true
        default: latest
      meilisearch:
        description: meilisearch image tag
        required: true
        default: v1.7.3
      express:
        description: Mongo express image tag
        required: true
        default: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Build container images'
        run: |
          docker pull mongo:${{ inputs.mongo }}
          docker tag mongo:${{ inputs.mongo }} ${{ secrets.ACR_REGISTRY }}/aksapp/${{ secrets.ACR_REPO }}:mongo_${{ inputs.mongo }}
          docker pull getmeili/meilisearch:${{ inputs.meilisearch }}
          docker tag getmeili/meilisearch:${{ inputs.meilisearch }} ${{ secrets.ACR_REGISTRY }}/aksapp/${{ secrets.ACR_REPO }}:meilisearch_${{ inputs.meilisearch }}
          docker pull mongo-express:${{ inputs.express }}
          docker tag mongo-express:${{ inputs.express }} ${{ secrets.ACR_REGISTRY }}/aksapp/${{ secrets.ACR_REPO }}:mongo-express_${{ inputs.express }}
          docker build . --file customize/Dockerfile --tag ${{ secrets.ACR_REGISTRY }}/aksapp/${{ secrets.ACR_REPO }}:librechat_${{ inputs.tag }}

      - name: 'Login ACR'
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_TOKENNAME }}
          password: ${{ secrets.ACR_TOKEN }}
      
      - name: 'Push container image to ACR'
        run: |
          docker push ${{ secrets.ACR_REGISTRY }}/aksapp/${{ secrets.ACR_REPO }}:librechat_${{ inputs.tag }}
          docker push ${{ secrets.ACR_REGISTRY }}/aksapp/${{ secrets.ACR_REPO }}:mongo_${{ inputs.mongo }}
          docker push ${{ secrets.ACR_REGISTRY }}/aksapp/${{ secrets.ACR_REPO }}:meilisearch_${{ inputs.meilisearch }}
          docker push ${{ secrets.ACR_REGISTRY }}/aksapp/${{ secrets.ACR_REPO }}:mongo-express_${{ inputs.express }}