name: Deploy Custom Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Input image tag
        required: true
        default: latest
      mongo:
        description: Input MongoDB image tag
        required: true
        default: latest
      meilisearch:
        description: Input meilisearch image tag
        required: true
        default: v1.7.3

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Azure login OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  
      - name: Kubelogin with AKS
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.1.4'
  
      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          admin: false
          cluster-name: ${{ secrets.AKS_CLUSTER }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          use-kubelogin: true
  
      - name: update yaml file with env variables
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          files: '["./customize/env-file","./customize/librechat-config.yaml"]'
        env:
          # for env-file
          URL: ${{ secrets.URL}}
          SMTP: ${{ secrets.SMTP}}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD}}
          SMTP_FROM_NAME: ${{ secrets.SMTP_FROM_NAME }}
          SMTP_FROM: ${{ secrets.SMTP_FROM }}
          CUSTOM_FOOTER: ${{ secrets.CUSTOM_FOOTER }}
          HELP: ${{ secrets.HELP }}
          # for librechat-config.yaml
          PRIVACYURL: ${{ secrets.PRIVACYURL }}
          TOSURL: ${{ secrets.TOSURL }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
          ENDPOINT_KEY: ${{ secrets.ENDPOINT_KEY }}
          ENDPOINT_URL: ${{ secrets.ENDPOINT_URL }}
  
      - name: Generate configmap checksum
        run: |
          echo CHECKSUM="$(cat ./customize/env-file ./customize/librechat-config.yaml | shasum | awk '{ print $1 }')" >> "$GITHUB_ENV"

      - name: update deployment file
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          files: '["./customize/librechat-deploy.yaml"]'
        env:
          CHECKSUM: ${{ env.CHECKSUM }}
          MONGO_IMAGE: ${{ secrets.ACR_REGISTRY }}/aksapp/${{ secrets.ACR_REPO }}:mongo_${{ inputs.mongo }}
          MEILI_IMAGE: ${{ secrets.ACR_REGISTRY }}/aksapp/${{ secrets.ACR_REPO }}:meilisearch_${{ inputs.meilisearch }}
          LIBRE_IMAGE: ${{ secrets.ACR_REGISTRY }}/aksapp/${{ secrets.ACR_REPO }}:librechat_${{ inputs.tag }}
          PVC_NAME: ${{ secrets.PVC_NAME }}
          SSL_CERT: ${{ secrets.SSL_CERT }}
          WAF_POLICY: ${{ secrets.WAF_POLICY }}

      - name: Deploy
        run: |
          kubectl create configmap librechat-config --from-file ./customize/librechat-config.yaml -o yaml --dry-run=client | kubectl apply -n ${{ secrets.NAMESPACE }} -f -
          kubectl create configmap librechat-env --from-env-file=./customize/env-file -o yaml --dry-run=client | kubectl apply -n ${{ secrets.NAMESPACE }} -f -
          kubectl apply -f ./customize/librechat-deploy.yaml -n ${{ secrets.NAMESPACE }}